const state={channels:[],visibleChannels:[],favorites:new Set(JSON.parse(localStorage.getItem('smartIptvFavs')||'[]')),filterMode:'all',currentUrl:'',hls:null};
const el={playlistUrl:document.getElementById('playlistUrl'),fileInput:document.getElementById('fileInput'),loadPlaylistBtn:document.getElementById('loadPlaylistBtn'),xtreamServer:document.getElementById('xtreamServer'),xtreamUser:document.getElementById('xtreamUser'),xtreamPass:document.getElementById('xtreamPass'),loadXtreamBtn:document.getElementById('loadXtreamBtn'),searchInput:document.getElementById('searchInput'),allBtn:document.getElementById('allBtn'),favBtn:document.getElementById('favBtn'),clearFavBtn:document.getElementById('clearFavBtn'),channelList:document.getElementById('channelList'),channelCount:document.getElementById('channelCount'),status:document.getElementById('status'),nowPlaying:document.getElementById('nowPlaying'),streamInfo:document.getElementById('streamInfo'),video:document.getElementById('video'),playPauseBtn:document.getElementById('playPauseBtn'),stopBtn:document.getElementById('stopBtn'),muteBtn:document.getElementById('muteBtn')};
function setStatus(t){el.status.textContent=t} function saveFavorites(){localStorage.setItem('smartIptvFavs',JSON.stringify([...state.favorites]))}
function parseM3U(content){const channels=[];let name='',logo='',epgId='';for(const raw of content.split(/\r?\n/)){const line=raw.trim();if(!line)continue;if(line.startsWith('#EXTINF')){const nm=line.match(/,(.*)$/),lg=line.match(/tvg-logo=\"([^\"]+)\"/),id=line.match(/tvg-id=\"([^\"]+)\"/);name=(nm?.[1]||'Unbekannt').trim();logo=(lg?.[1]||'').trim();epgId=(id?.[1]||'').trim()}else if(/^(https?|rtmp|rtsp|udp|mms):\/\//i.test(line)){channels.push({name,url:line,logo,epgId});name='';logo='';epgId=''}}return channels}
function setChannels(channels,source='Playlist'){state.channels=channels;state.filterMode='all';renderChannels();setStatus(`${source} geladen: ${channels.length} Sender`);el.nowPlaying.textContent='Kein Sender aktiv';el.streamInfo.textContent='Wähle links einen Sender aus.'}
function renderChannels(){const q=el.searchInput.value.trim().toLowerCase();let list=state.channels.slice();if(state.filterMode==='fav')list=list.filter(ch=>state.favorites.has(ch.url));if(q)list=list.filter(ch=>ch.name.toLowerCase().includes(q));state.visibleChannels=list;el.channelCount.textContent=`Sender: ${list.length}`;el.channelList.innerHTML='';list.forEach(ch=>{const li=document.createElement('li');if(ch.url===state.currentUrl)li.classList.add('active');const star=document.createElement('span');star.className='star';star.textContent=state.favorites.has(ch.url)?'★':'☆';star.addEventListener('click',ev=>{ev.stopPropagation();if(state.favorites.has(ch.url))state.favorites.delete(ch.url);else state.favorites.add(ch.url);saveFavorites();renderChannels()});const text=document.createElement('div');text.textContent=ch.name||'Unbekannt';li.appendChild(star);li.appendChild(text);li.addEventListener('click',()=>playChannel(ch));el.channelList.appendChild(li)})}
function destroyHls(){if(state.hls){state.hls.destroy();state.hls=null}}
function playChannel(channel){if(!channel?.url)return;destroyHls();const url=channel.url;state.currentUrl=url;el.nowPlaying.textContent=channel.name||'Unbekannt';el.streamInfo.textContent=url;if(window.Hls&&Hls.isSupported()&&/\.m3u8($|\?)/i.test(url)){state.hls=new Hls();state.hls.loadSource(url);state.hls.attachMedia(el.video);state.hls.on(Hls.Events.MANIFEST_PARSED,()=>{el.video.play().catch(()=>{})})}else{el.video.src=url;el.video.play().catch(()=>{})}setStatus(`Spielt: ${channel.name||'Unbekannt'}`);renderChannels()}
async function loadPlaylistFromUrl(){const url=el.playlistUrl.value.trim();if(!url){alert('Bitte Playlist URL eingeben.');return}setStatus('Lade Playlist...');try{const res=await fetch(url);if(!res.ok)throw new Error(`HTTP ${res.status}`);const text=await res.text();const channels=parseM3U(text);if(!channels.length)throw new Error('Keine Streams gefunden. Eventuell CORS oder ungültige Playlist.');setChannels(channels,'Playlist')}catch(err){setStatus('Playlist konnte nicht geladen werden');alert('Fehler beim Laden der Playlist:\n'+err.message)}}
function loadPlaylistFromFile(file){const reader=new FileReader();reader.onload=()=>{const text=String(reader.result||'');const channels=parseM3U(text);if(!channels.length){alert('Keine Streams in der Datei gefunden.');return}setChannels(channels,file.name)};reader.readAsText(file,'utf-8')}
async function loadXtream(){const server=el.xtreamServer.value.trim().replace(/\/+$/,''),username=el.xtreamUser.value.trim(),password=el.xtreamPass.value.trim();if(!server||!username||!password){alert('Xtream Server, Benutzername und Passwort eingeben.');return}setStatus('Xtream wird geladen...');try{const authUrl=`${server}/player_api.php?username=${encodeURIComponent(username)}&password=${encodeURIComponent(password)}`;const authRes=await fetch(authUrl);if(!authRes.ok)throw new Error(`HTTP ${authRes.status}`);const authData=await authRes.json();const ok=authData?.user_info?.auth;if(!(ok===1||ok==='1'||ok===true))throw new Error('Ungültige Xtream-Zugangsdaten');const streamsRes=await fetch(`${authUrl}&action=get_live_streams`);if(!streamsRes.ok)throw new Error(`HTTP ${streamsRes.status}`);const streams=await streamsRes.json();const channels=[];for(const item of streams){if(!item?.stream_id)continue;const ext=String(item.container_extension||'ts').replace(/^\.+/,'');channels.push({name:item.name||item.stream_display_name||'Unbekannt',url:`${server}/live/${username}/${password}/${item.stream_id}.${ext}`,logo:item.stream_icon||'',epgId:String(item.epg_channel_id||'')})}if(!channels.length)throw new Error('Keine Live-Sender gefunden');setChannels(channels,'Xtream')}catch(err){setStatus('Xtream konnte nicht geladen werden');alert('Xtream Fehler:\n'+err.message+'\n\nHinweis: Browser kann wegen CORS blockieren.')}}
el.loadPlaylistBtn.addEventListener('click',loadPlaylistFromUrl);
el.fileInput.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)loadPlaylistFromFile(file)});
el.loadXtreamBtn.addEventListener('click',loadXtream);
el.searchInput.addEventListener('input',renderChannels);
el.allBtn.addEventListener('click',()=>{state.filterMode='all';renderChannels()});
el.favBtn.addEventListener('click',()=>{state.filterMode='fav';renderChannels()});
el.clearFavBtn.addEventListener('click',()=>{state.favorites.clear();saveFavorites();renderChannels()});
el.playPauseBtn.addEventListener('click',()=>{if(el.video.paused)el.video.play().catch(()=>{});else el.video.pause()});
el.stopBtn.addEventListener('click',()=>{destroyHls();el.video.pause();el.video.removeAttribute('src');el.video.load();state.currentUrl='';el.nowPlaying.textContent='Kein Sender aktiv';el.streamInfo.textContent='Wähle links einen Sender aus.';setStatus('Gestoppt');renderChannels()});
el.muteBtn.addEventListener('click',()=>{el.video.muted=!el.video.muted});
setStatus('Bereit');renderChannels();
